
spring.application.name=sincronizador2

# ===============================
# CONFIGURACIÓN DE POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5434/sincronizador_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
# update: Crea o actualiza las tablas automáticamente según tus @Entity
spring.jpa.hibernate.ddl-auto=update

# Muestra el SQL que Spring genera por debajo (muy útil para debuggear)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

minio.endpoint=http://68.183.126.34:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin123
minio.bucket=sync-data