spring.application.name=sincronizador2

# ===============================
# CONFIGURACIÓN DE POSTGRESQL (LOCAL / desarrollo en tu Mac)
# ===============================
spring.datasource.url=jdbc:postgresql://68.183.126.34:5434/sincronizador_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# MINIO
# ===============================
minio.endpoint=http://68.183.126.34:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin123
minio.bucket=sync-data

# ===============================
# SWAGGER / OPENAPI
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs